PS1='[\[\e[31;1m\]\u\[\e[33;1m\]@\[\e[32;1m\]\h \[\e[m\]\w \$]'
if [ -f /etc/bashrc ]; then
            . /etc/bashrc
fi

function opcd()
{
   date=`date +'%Y%m%d'`
   basedir="/data/opdir/"
   tar=$1
   dir=${basedir}${date}${tar}
   if [  -d $dir ]
   then 
        cd $dir
   else
        mkdir $dir && cd $dir
   fi 

}
